import type { Movie } from '@/types'

export const MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Dune: Parte Dos',
    genre: ['Ciencia Ficción', 'Aventura'],
    duration: 166,
    rating: 8.5,
    price: 18,
    image: 'https://images.justwatch.com/poster/305017949/s718/dune-parte-dos.jpg',
    description: 'Paul Atreides se une a los Fremen en su guerra contra los Harkonnen.',
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson'],
    showtimes: [
      { id: 's1', date: '2026-05-25', time: '16:00', availableSeats: 45 },
      { id: 's2', date: '2026-05-25', time: '19:30', availableSeats: 30 },
      { id: 's3', date: '2026-05-26', time: '20:00', availableSeats: 50 },
    ],
  },
  {
    id: '2',
    title: 'Oppenheimer',
    genre: ['Drama', 'Historia'],
    duration: 180,
    rating: 8.9,
    price: 20,
    image: 'https://images.justwatch.com/poster/248469974/s718/oppenheimer.jpg',
    description: 'La historia del físico que lideró el Proyecto Manhattan.',
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon'],
    showtimes: [
      { id: 's4', date: '2026-05-25', time: '15:00', availableSeats: 20 },
      { id: 's5', date: '2026-05-26', time: '18:30', availableSeats: 35 },
    ],
  },
  {
    id: '3',
    title: 'Poor Things',
    genre: ['Comedia', 'Romance'],
    duration: 141,
    rating: 8.0,
    price: 16,
    image: 'https://images.justwatch.com/poster/305396328/s718/pobres-criaturas.jpg',
    description: 'Una joven resucitada por un científico excéntrico explora el mundo.',
    director: 'Yorgos Lanthimos',
    cast: ['Emma Stone', 'Mark Ruffalo', 'Willem Dafoe'],
    showtimes: [
      { id: 's6', date: '2026-05-25', time: '18:00', availableSeats: 40 },
      { id: 's7', date: '2026-05-27', time: '21:00', availableSeats: 25 },
    ],
  },
  {
    id: '4',
    title: 'Killers of the Flower Moon',
    genre: ['Drama', 'Crimen'],
    duration: 206,
    rating: 7.7,
    price: 20,
    image: 'https://images.justwatch.com/poster/300928216/s718/los-asesinos-de-la-luna.jpg',
    description: 'Los asesinatos en serie de miembros de la nación Osage en los años 20.',
    director: 'Martin Scorsese',
    cast: ['Leonardo DiCaprio', 'Robert De Niro', 'Lily Gladstone'],
    showtimes: [
      { id: 's8', date: '2026-05-26', time: '14:00', availableSeats: 15 },
      { id: 's9', date: '2026-05-27', time: '17:30', availableSeats: 30 },
    ],
  },
  {
    id: '5',
    title: 'The Zone of Interest',
    genre: ['Drama', 'Historia'],
    duration: 105,
    rating: 7.9,
    price: 16,
    image: 'https://placehold.co/500x750/27272a/ffffff?text=Zone+of+Interest',
    description: 'El comandante de Auschwitz y su familia construyen su vida ideal junto al campo.',
    director: 'Jonathan Glazer',
    cast: ['Christian Friedel', 'Sandra Hüller'],
    showtimes: [
      { id: 's10', date: '2026-05-25', time: '20:30', availableSeats: 50 },
      { id: 's11', date: '2026-05-28', time: '19:00', availableSeats: 45 },
    ],
  },
  {
    id: '6',
    title: 'Saltburn',
    genre: ['Thriller', 'Drama'],
    duration: 127,
    rating: 7.1,
    price: 16,
    image: 'https://images.justwatch.com/poster/301715838/s718/saltburn.jpg',
    description: 'Un estudiante obsesionado con su carismático compañero visita su extravagante mansión.',
    director: 'Emerald Fennell',
    cast: ['Barry Keoghan', 'Jacob Elordi', 'Rosamund Pike'],
    showtimes: [
      { id: 's12', date: '2026-05-26', time: '21:30', availableSeats: 35 },
      { id: 's13', date: '2026-05-28', time: '20:00', availableSeats: 40 },
    ],
  },
]